# 配置网关
spring:
  cloud:
    gateway:
      routes:
        - id: taowu-user
          uri: lb://taowu-user
          predicates:
            - Path=/user/**  # 访问user路径转发用户服务
        - id: taowu-product
          uri: lb://taowu-product #使用负载均衡,调用服务名,这是服务名
          predicates:
            - Path=/product/** # 访问product相关,转发到product服务